language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_0f725f212537_key -iv $encrypted_0f725f212537_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -dopenssl aes-256-cbc -K $encrypted_616d7d57915c_key -iv $encrypted_616d7d57915c_iv -in application.properties.enc -out src/main/resources/application.properties -d

